<?php

declare (strict_types=1);
namespace App\GraphQL\Representation;

use App\GraphQL\Mapper\EntityToGQLModel;
use App\GraphQL\Model\CodedCurrencyType;
use App\Repository\CodedCurrencyRepository;
use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Federation\Representation;
use Axtiva\FlexibleGraphql\Federation\Resolver\FederationRepresentationResolverInterface;
use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Representation resolver for federated graphql type CodedCurrency
 */
final class CodedCurrencyRepresentation implements FederationRepresentationResolverInterface
{
    private CodedCurrencyRepository $codedCurrencyRepository;

    public function __construct(CodedCurrencyRepository $codedCurrencyRepository)
    {
        $this->codedCurrencyRepository = $codedCurrencyRepository;
    }

    public function getTypeName(): string
    {
        return 'CodedCurrency';
    }

    public function __invoke(Representation $representation, $context, ResolveInfo $info)
    {
        $id = $representation->getFields()['code']; // array from CodedCurrency @key(fields: "code")
        $entity = $this->codedCurrencyRepository->find($id);
        if ($entity) {
            $response = new CodedCurrencyType();
            EntityToGQLModel::codedCurrency($entity, $response);

            return $response;
        }

        return null;
    }
}