<?php

declare (strict_types=1);
namespace App\GraphQL\Scalar;

use DateTimeImmutable;
use GraphQL\Language\AST\Node;
use Axtiva\FlexibleGraphql\Resolver\CustomScalarResolverInterface;
use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for scalar DateTime
 * Format: ISO8601 YYYY-MM-DDTHH:MM:SS+0000
 */
final class DateTimeScalar implements CustomScalarResolverInterface
{
    public function serialize($value)
    {
        return $value->format(DateTimeImmutable::ISO8601);
    }

    public function parseValue($value)
    {
        return $value ? new DateTimeImmutable($value) : null;
    }

    public function parseLiteral(Node $value, ?array $variables = null)
    {
        return $value->value ? new DateTimeImmutable((string) $value->value) : null;
    }
}