<?php

declare (strict_types=1);
namespace App\GraphQL\Scalar;

use DateTimeImmutable;
use GraphQL\Error\UserError;
use GraphQL\Language\AST\Node;
use Axtiva\FlexibleGraphql\Resolver\CustomScalarResolverInterface;
use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for scalar Time
 * Format: HH:MM:SS
 */
final class TimeScalar implements CustomScalarResolverInterface
{
    /**
     * @param DateTimeImmutable $value
     */
    public function serialize($value)
    {
        return $value ? $value->format('H:i:s') : null;
    }

    public function parseValue($value)
    {
        return $this->parse($value);
    }

    public function parseLiteral(Node $value, ?array $variables = null)
    {
        return $this->parse($value->value ?? null);

    }

    private function parse($value)
    {
        if ($value === null) {
            return null;
        }

        $time = DateTimeImmutable::createFromFormat('H:i:s', $value);
        if ($time === false) {
            throw new UserError('Unsupported format, only HH:MM:SS');
        }

        return $time;

    }
}