<?php

declare (strict_types=1);
namespace SelfWritten\GraphQL\UnionResolveType;

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\UnionResolveTypeInterface;
use SelfWritten\GraphQL\Model\TransactionType;
use SelfWritten\GraphQL\Model\AccountType;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * and will be regenerated. Do not edit it manually
 */
final class _EntityTypeResolver implements UnionResolveTypeInterface
{
    public function __invoke($model, $context, ResolveInfo $info)
    {
        if (isset($model)) {
            switch (get_class($model)) {
                case TransactionType::class:
                    return $info->schema->getType('Transaction');
                case AccountType::class:
                    return $info->schema->getType('Account');
            }
        }
        return null;
    }
}