<?php

declare (strict_types=1);
namespace SelfWritten\GraphQL\UnionResolveType;

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\UnionResolveTypeInterface;
use SelfWritten\GraphQL\Model\TransactionMessageLogType;
use SelfWritten\GraphQL\Model\TransactionCodeLogType;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * and will be regenerated. Do not edit it manually
 */
final class TransactionLogTypeResolver implements UnionResolveTypeInterface
{
    public function __invoke($model, $context, ResolveInfo $info)
    {
        if (isset($model)) {
            switch (get_class($model)) {
                case TransactionMessageLogType::class:
                    return $info->schema->getType('TransactionMessageLog');
                case TransactionCodeLogType::class:
                    return $info->schema->getType('TransactionCodeLog');
            }
        }
        return null;
    }
}