<?php

declare (strict_types=1);
namespace SelfWritten\GraphQL\Resolver\Query;

use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;
use DateTimeImmutable;
use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for Query.date
 */
final class DateResolver implements ResolverInterface
{
    function __invoke($rootValue, $args, $context, ResolveInfo $info)
    {
        return new DateTimeImmutable();
    }
}