<?php

declare (strict_types=1);
namespace SelfWritten\GraphQL\Resolver\Query;

use DateTimeImmutable;
use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;
use SelfWritten\GraphQL\ResolverArgs\Query\DayTimeResolverArgs;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for Query.dayTime
 */
final class DayTimeResolver implements ResolverInterface
{
    /**
     * @param $rootValue
     * @param DayTimeResolverArgs $args
     * @param $context
     * @param ResolveInfo $info
     * @return iterable|DateTimeImmutable[]
     */
    public function __invoke($rootValue, $args, $context, ResolveInfo $info)
    {
        foreach ($args->timestamps as $ts1) {
            foreach ($ts1 as $ts2) {
                yield \DateTimeImmutable::createFromFormat('U', (string)$ts2->ts);
            }
        }
    }
}