<?php

declare (strict_types=1);
namespace SelfWritten\GraphQL\Directive;

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\DirectiveResolverInterface;
use SelfWritten\GraphQL\DirectiveArgs\PowDirectiveArgs;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Resolver for executable directive @pow
 */
final class PowDirective implements DirectiveResolverInterface
{
    /**
     * @param callable $next
     * @param PowDirectiveArgs $directiveArgs
     * @param $rootValue
     * @param $args
     * @param $context
     * @param ResolveInfo $info
     * @return mixed
     */
    public function __invoke(callable $next, $directiveArgs, $rootValue, $args, $context, ResolveInfo $info)
    {
        $result = $next($rootValue, $args, $context, $info);

        return $result ** $directiveArgs->ex;
    }
}