<?php

declare (strict_types=1);
namespace SelfWritten\GraphQL\Scalar;

use Axtiva\FlexibleGraphql\Resolver\TypedCustomScalarResolverInterface;
use DateTimeImmutable;
use GraphQL\Language\AST\Node;
use Axtiva\FlexibleGraphql\Resolver\CustomScalarResolverInterface;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for scalar DateTime
 */
final class DateTimeScalar implements TypedCustomScalarResolverInterface
{
    public function serialize($value)
    {
        return $value->format(DateTimeImmutable::RFC3339);
    }

    public function parseValue($value)
    {
        return $value ? new DateTimeImmutable($value) : null;
    }

    public function parseLiteral(Node $value, ?array $variables = null)
    {
        return $value->value ? new DateTimeImmutable((string) $value->value) : null;
    }

    public static function getTypeName(): ?string
    {
        return DateTimeImmutable::class;
    }
}