<?php

declare (strict_types=1);
namespace App\GraphQL\Resolver\Query;

use App\GraphQL\Model\UserType;
use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;
use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for Query.currentUser
 */
final class CurrentUserResolver implements ResolverInterface
{
    function __invoke($rootValue, $args, $context, ResolveInfo $info)
    {
        $user = $context->getUser();
        if ($user) {
            $response = new UserType();
            $response->username = $user->getUserIdentifier();
            $response->role = $user->getRoles()[0];

            return $response;
        }

        return null;
    }
}