<?php

declare (strict_types=1);
namespace SelfWritten\GraphQL\Model;

use Axtiva\FlexibleGraphql\Type\InputType;

/**
 * This code is @generated by axtiva/flexible-graphql-php do not edit it
 * PHP representation of graphql type SumInput
 * @property int $x 
 * @property int $y 
 */
final class SumInputInputType extends InputType
{
    protected function decorate($name, $value)
    {
        if ($value === null) {
            return null;
        }

        return $value;
    }
}