<?php

declare (strict_types=1);
namespace SelfWritten\GraphQL\Model;

use Axtiva\FlexibleGraphql\Generator\Exception\UnknownEnumValue;
use Axtiva\FlexibleGraphql\Type\EnumInterface;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * and will be regenerated. Do not edit it manually
 * PHP representation of graphql enum TransactionStatus
 */
final class TransactionStatusEnum implements EnumInterface
{
    public const IN_PROGRESS = 'IN_PROGRESS';
    public const SUCCESS = 'SUCCESS';
    public const FAIL = 'FAIL';
    public string $value;
    private static array $map = [
        self::IN_PROGRESS => true,
        self::SUCCESS => true,
        self::FAIL => true,
    ];

    public function __construct($value)
    {
        if (!isset(self::$map[$value])) {
            throw new UnknownEnumValue(__CLASS__, $value);
        }
        $this->value = $value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}