<?php

declare (strict_types=1);
namespace SelfWritten\GraphQL\ResolverArgs\Query;

use Axtiva\FlexibleGraphql\Type\InputType;
use SelfWritten\GraphQL\Model\SumInputInputType;

/**
 * This code is @generated by axtiva/flexible-graphql-php do not edit it
 * PHP representation of graphql field args of Query.sum
 * @property SumInputInputType $sumInput 
 */
final class SumResolverArgs extends InputType
{
    protected function decorate($name, $value)
    {
        if ($value === null) {
            return null;
        }

        if ($name === 'sumInput') {
            return new SumInputInputType($value);
        }

        return $value;
    }
}