<?php

declare (strict_types=1);
namespace App\GraphQL\ResolverArgs\Query;

use Axtiva\FlexibleGraphql\Type\InputType;
use App\GraphQL\Model\TimestampInputInputType;

/**
 * This code is @generated by axtiva/flexible-graphql-php do not edit it
 * PHP representation of graphql field args of Query.dayTime
 * @property iterable|TimestampInputInputType[][] $timestamps 
 */
final class DayTimeResolverArgs extends InputType
{
    protected function decorate($name, $value)
    {
        if ($value === null) {
            return null;
        }

        if ($name === 'timestamps') {
            return (function($value) {foreach($value as $v) yield (function($value) {foreach($value as $v) yield ($v === null ? null : new TimestampInputInputType($v)); })($v); })($value);
        }

        return $value;
    }
}