<?php

declare (strict_types=1);
namespace App\GraphQL\ResolverArgs\Query;

use Axtiva\FlexibleGraphql\Type\InputType;
use App\GraphQL\Model\ModInputInputType;

/**
 * This code is @generated by axtiva/flexible-graphql-php do not edit it
 * PHP representation of graphql field args of Query.mod
 * @property ModInputInputType $input 
 */
final class ModResolverArgs extends InputType
{
    protected function decorate($name, $value)
    {
        if ($value === null) {
            return null;
        }

        if ($name === 'input') {
            return new ModInputInputType($value);
        }

        return $value;
    }
}