<?php

declare (strict_types=1);
namespace App\GraphQL\Directive;

use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;
use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\DirectiveResolverInterface;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Resolver for executable directive @pow
 */
final class PowDirective implements DirectiveResolverInterface
{
    function __invoke(callable $next, $directiveArgs, $rootValue, $args, $context, ResolveInfo $info)
    {
        $result = $next($rootValue, $args, $context, $info);

        return $result ** $directiveArgs['ex'];
    }
}