<?php
/**
 * Autogenerated file by axtiva/flexible-graphql-php Do not edit it manually
 */ 
namespace SelfWritten\GraphQL;

use GraphQL\Type\Definition\Type;
use GraphQL\Type\Definition\InterfaceType;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\ListOfType;
use GraphQL\Type\Definition\NonNull;
use Axtiva\FlexibleGraphql\Type\EnumType;
use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\CustomScalarType;
use GraphQL\Type\Definition\UnionType;
use GraphQL\Type\Definition\Directive;
use GraphQL\Type\Definition\FieldArgument;
use GraphQL\Type\Definition\FieldDefinition;
use GraphQL\Type\Definition\InputObjectField;
use Psr\Container\ContainerInterface;
use GraphQL\Type\Schema;

class TypeRegistry
{
    private ContainerInterface $container;
    
    /**
     * @var array<string, Type>
     */
    private array $types = [];
    
    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    public function getType(string $name): Type
    {
        return $this->types[$name] ??= $this->{$name}();
    }
    
    
            public function Query()
            {
                return new ObjectType([
            'name' => 'Query',
            'description' => NULL,
            'fields' => fn() => ['sum' => FieldDefinition::create([
            'name' => 'sum',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => function($rootValue, $args, $context, $info) {
                        return $this->container->get('SelfWritten\GraphQL\Directive\IsAuthenticatedDirective')(
                        function($rootValue, $args, $context, $info) {
                        return $this->container->get('SelfWritten\GraphQL\Directive\PowDirective')(
                        (function ($rootValue, $args, $context, $info) {
    $args = new \SelfWritten\GraphQL\ResolverArgs\Query\SumResolverArgs($args);
    return $this->container->get('SelfWritten\GraphQL\Resolver\Query\SumResolver')($rootValue, $args, $context, $info);
}), 
                        new \SelfWritten\GraphQL\DirectiveArgs\PowDirectiveArgs(array (
  'ex' => '3',
)),
                        $rootValue, $args, $context, $info
                        );
                    }, 
                        array (
),
                        $rootValue, $args, $context, $info
                        );
                    },
            'type' => function() { return Type::nonNull(function() { return Type::int(); }); },
            'args' => ['sumInput' => [
            'name' => 'sumInput',
            'type' => function() { return Type::nonNull(function() { return $this->getType('SumInput'); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]],
        ]),'date' => FieldDefinition::create([
            'name' => 'date',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => function($rootValue, $args, $context, $info) {
                        return $this->container->get('SelfWritten\GraphQL\Directive\HasRoleDirective')(
                        (function ($rootValue, $args, $context, $info) {
    
    return $this->container->get('SelfWritten\GraphQL\Resolver\Query\DateResolver')($rootValue, $args, $context, $info);
}), 
                        new \SelfWritten\GraphQL\DirectiveArgs\HasRoleDirectiveArgs(array (
  'role' => 'admin',
)),
                        $rootValue, $args, $context, $info
                        );
                    },
            'type' => function() { return Type::nonNull(function() { return $this->getType('DateTime'); }); },
            'args' => [],
        ]),'dayTime' => FieldDefinition::create([
            'name' => 'dayTime',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => (function ($rootValue, $args, $context, $info) {
    $args = new \SelfWritten\GraphQL\ResolverArgs\Query\DayTimeResolverArgs($args);
    return $this->container->get('SelfWritten\GraphQL\Resolver\Query\DayTimeResolver')($rootValue, $args, $context, $info);
}),
            'type' => function() { return new ListOfType(function() { return $this->getType('DateTime'); }); },
            'args' => ['timestamps' => [
            'name' => 'timestamps',
            'type' => function() { return Type::nonNull(function() { return new ListOfType(function() { return Type::nonNull(function() { return new ListOfType(function() { return Type::nonNull(function() { return $this->getType('TimestampInput'); }); }); }); }); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]],
        ]),'_service' => FieldDefinition::create([
            'name' => '_service',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => (function ($rootValue, $args, $context, $info) {
    
    return $this->container->get('SelfWritten\GraphQL\Resolver\Query\_serviceResolver')($rootValue, $args, $context, $info);
}),
            'type' => function() { return Type::nonNull(function() { return $this->getType('_Service'); }); },
            'args' => [],
        ]),'_entities' => FieldDefinition::create([
            'name' => '_entities',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => (function ($rootValue, $args, $context, $info) {
    $args = new \SelfWritten\GraphQL\ResolverArgs\Query\_entitiesResolverArgs($args);
    return $this->container->get('SelfWritten\GraphQL\Resolver\Query\_entitiesResolver')($rootValue, $args, $context, $info);
}),
            'type' => function() { return Type::nonNull(function() { return new ListOfType(function() { return $this->getType('_Entity'); }); }); },
            'args' => ['representations' => [
            'name' => 'representations',
            'type' => function() { return Type::nonNull(function() { return new ListOfType(function() { return Type::nonNull(function() { return $this->getType('_Any'); }); }); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]],
        ])],
        ]);
            }
        


            public function SumInput()
            {
                return new InputObjectType([
        'name' => 'SumInput',
        'description' =>  NULL,
        'fields' => fn() => ['x' => [
            'name' => 'x',
            'description' => NULL,
            'defaultValue' => NULL,
            'type' => Type::nonNull(function() { return Type::int(); }),
        ],'y' => [
            'name' => 'y',
            'description' => NULL,
            'defaultValue' => NULL,
            'type' => Type::nonNull(function() { return Type::int(); }),
        ]],
        ]);
            }
        


            public function DateTime()
            {
                return new CustomScalarType([
            'name' => 'DateTime',
            'description' => NULL,
            'serialize' => function($value) {return ($this->container->get('SelfWritten\GraphQL\Scalar\DateTimeScalar'))->serialize($value);},
            'parseValue' => function($value) {return ($this->container->get('SelfWritten\GraphQL\Scalar\DateTimeScalar'))->parseValue($value);},
            'parseLiteral' => function($value, $variables) {return ($this->container->get('SelfWritten\GraphQL\Scalar\DateTimeScalar'))->parseLiteral($value, $variables);},
        ]);
            }
        


            public function TimestampInput()
            {
                return new InputObjectType([
        'name' => 'TimestampInput',
        'description' =>  NULL,
        'fields' => fn() => ['ts' => [
            'name' => 'ts',
            'description' => NULL,
            'defaultValue' => NULL,
            'type' => Type::nonNull(function() { return Type::int(); }),
        ]],
        ]);
            }
        


            public function _Service()
            {
                return new ObjectType([
            'name' => '_Service',
            'description' => NULL,
            'fields' => fn() => ['sdl' => FieldDefinition::create([
            'name' => 'sdl',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return Type::nonNull(function() { return Type::string(); }); },
            'args' => [],
        ])],
        ]);
            }
        


            public function _Any()
            {
                return new CustomScalarType([
            'name' => '_Any',
            'description' => NULL,

        ]);
            }
        


            public function _Entity()
            {
                return new UnionType([
            'name' => '_Entity',
            'description' => NULL,
            'types' => function() { return [$this->getType('Transaction'),$this->getType('Account')];},
            'resolveType' => $this->container->get('SelfWritten\GraphQL\UnionResolveType\_EntityTypeResolver'),
        ]);
            }
        


            public function Transaction()
            {
                return new ObjectType([
            'name' => 'Transaction',
            'description' => NULL,
            'fields' => fn() => ['id' => FieldDefinition::create([
            'name' => 'id',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return Type::nonNull(function() { return Type::id(); }); },
            'args' => [],
        ]),'amount' => FieldDefinition::create([
            'name' => 'amount',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return Type::nonNull(function() { return Type::int(); }); },
            'args' => [],
        ]),'status' => FieldDefinition::create([
            'name' => 'status',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return Type::nonNull(function() { return $this->getType('TransactionStatus'); }); },
            'args' => [],
        ]),'account' => FieldDefinition::create([
            'name' => 'account',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return Type::nonNull(function() { return $this->getType('Account'); }); },
            'args' => [],
        ]),'log' => FieldDefinition::create([
            'name' => 'log',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return new ListOfType(function() { return Type::nonNull(function() { return $this->getType('TransactionLog'); }); }); },
            'args' => [],
        ]),'createdAt' => FieldDefinition::create([
            'name' => 'createdAt',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return Type::nonNull(function() { return $this->getType('DateTime'); }); },
            'args' => [],
        ])],
        ]);
            }
        


            public function TransactionStatus()
            {
                return new EnumType([
        'name' => 'TransactionStatus',
        'description' => NULL,
        'values' => ['IN_PROGRESS' => [
            'name' => 'IN_PROGRESS', 
            'value' => 'IN_PROGRESS',
            'description' => NULL,
            'deprecationReason' => NULL,
            ],
'SUCCESS' => [
            'name' => 'SUCCESS', 
            'value' => 'SUCCESS',
            'description' => NULL,
            'deprecationReason' => NULL,
            ],
'FAIL' => [
            'name' => 'FAIL', 
            'value' => 'FAIL',
            'description' => NULL,
            'deprecationReason' => NULL,
            ]],
        ]);
            }
        


            public function Account()
            {
                return new ObjectType([
            'name' => 'Account',
            'description' => NULL,
            'fields' => fn() => ['id' => FieldDefinition::create([
            'name' => 'id',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return Type::nonNull(function() { return Type::id(); }); },
            'args' => [],
        ]),'transactions' => FieldDefinition::create([
            'name' => 'transactions',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => (function ($rootValue, $args, $context, $info) {
    
    return $this->container->get('SelfWritten\GraphQL\Resolver\Account\TransactionsResolver')($rootValue, $args, $context, $info);
}),
            'type' => function() { return Type::nonNull(function() { return new ListOfType(function() { return Type::nonNull(function() { return $this->getType('Transaction'); }); }); }); },
            'args' => [],
        ])],
        ]);
            }
        


            public function TransactionLog()
            {
                return new UnionType([
            'name' => 'TransactionLog',
            'description' => NULL,
            'types' => function() { return [$this->getType('TransactionMessageLog'),$this->getType('TransactionCodeLog')];},
            'resolveType' => $this->container->get('SelfWritten\GraphQL\UnionResolveType\TransactionLogTypeResolver'),
        ]);
            }
        


            public function TransactionMessageLog()
            {
                return new ObjectType([
            'name' => 'TransactionMessageLog',
            'description' => NULL,
            'fields' => fn() => ['message' => FieldDefinition::create([
            'name' => 'message',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return Type::nonNull(function() { return Type::string(); }); },
            'args' => [],
        ])],
        ]);
            }
        


            public function TransactionCodeLog()
            {
                return new ObjectType([
            'name' => 'TransactionCodeLog',
            'description' => NULL,
            'fields' => fn() => ['code' => FieldDefinition::create([
            'name' => 'code',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return Type::nonNull(function() { return Type::int(); }); },
            'args' => [],
        ])],
        ]);
            }
        


            public function Mutation()
            {
                return new ObjectType([
            'name' => 'Mutation',
            'description' => NULL,
            'fields' => fn() => ['createTransaction' => FieldDefinition::create([
            'name' => 'createTransaction',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => (function ($rootValue, $args, $context, $info) {
    $args = new \SelfWritten\GraphQL\ResolverArgs\Mutation\CreateTransactionResolverArgs($args);
    return $this->container->get('SelfWritten\GraphQL\Resolver\Mutation\CreateTransactionResolver')($rootValue, $args, $context, $info);
}),
            'type' => function() { return $this->getType('Transaction'); },
            'args' => ['accountId' => [
            'name' => 'accountId',
            'type' => function() { return Type::nonNull(function() { return Type::id(); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ],'amount' => [
            'name' => 'amount',
            'type' => function() { return Type::nonNull(function() { return Type::int(); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]],
        ])],
        ]);
            }
        


            public function link__Purpose()
            {
                return new EnumType([
        'name' => 'link__Purpose',
        'description' => NULL,
        'values' => ['SECURITY' => [
            'name' => 'SECURITY', 
            'value' => 'SECURITY',
            'description' => '`SECURITY` features provide metadata necessary to securely resolve fields.',
            'deprecationReason' => NULL,
            ],
'EXECUTION' => [
            'name' => 'EXECUTION', 
            'value' => 'EXECUTION',
            'description' => '`EXECUTION` features provide metadata necessary for operation execution.',
            'deprecationReason' => NULL,
            ]],
        ]);
            }
        


            public function link__Import()
            {
                return new CustomScalarType([
            'name' => 'link__Import',
            'description' => NULL,

        ]);
            }
        


            public function FieldSet()
            {
                return new CustomScalarType([
            'name' => 'FieldSet',
            'description' => NULL,

        ]);
            }
        


    public function directive_link()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'link',
            'description' => 'Apollo federation directives',
            'isRepeatable' => false,
            'locations' => ['SCHEMA'],
            'args' => [
                [
            'name' => 'url',
            'type' => function() { return Type::string(); },
            'defaultValue' => NULL,
            'description' => NULL,
        ],[
            'name' => 'as',
            'type' => function() { return Type::string(); },
            'defaultValue' => NULL,
            'description' => NULL,
        ],[
            'name' => 'for',
            'type' => function() { return $this->getType('link__Purpose'); },
            'defaultValue' => NULL,
            'description' => NULL,
        ],[
            'name' => 'import',
            'type' => function() { return new ListOfType(function() { return $this->getType('link__Import'); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_external()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'external',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [
                
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_requires()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'requires',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [
                [
            'name' => 'fields',
            'type' => function() { return Type::nonNull(function() { return $this->getType('FieldSet'); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_provides()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'provides',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [
                [
            'name' => 'fields',
            'type' => function() { return Type::nonNull(function() { return $this->getType('FieldSet'); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_key()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'key',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['OBJECT','INTERFACE'],
            'args' => [
                [
            'name' => 'fields',
            'type' => function() { return Type::nonNull(function() { return $this->getType('FieldSet'); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ],[
            'name' => 'resolvable',
            'type' => function() { return Type::boolean(); },
            'defaultValue' => true,
            'description' => NULL,
        ]
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_shareable()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'shareable',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['OBJECT','FIELD_DEFINITION'],
            'args' => [
                
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_inaccessible()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'inaccessible',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION','OBJECT','INTERFACE','UNION','ARGUMENT_DEFINITION','SCALAR','ENUM','ENUM_VALUE','INPUT_OBJECT','INPUT_FIELD_DEFINITION'],
            'args' => [
                
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_override()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'override',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [
                [
            'name' => 'from',
            'type' => function() { return Type::nonNull(function() { return Type::string(); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_extends()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'extends',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['OBJECT','INTERFACE'],
            'args' => [
                
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_isAuthenticated()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'isAuthenticated',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD','FIELD_DEFINITION'],
            'args' => [
                
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_hasRole()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'hasRole',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD','FIELD_DEFINITION'],
            'args' => [
                [
            'name' => 'role',
            'type' => function() { return Type::string(); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_pow()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'pow',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD','FIELD_DEFINITION'],
            'args' => [
                [
            'name' => 'ex',
            'type' => function() { return Type::nonNull(function() { return Type::int(); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_uppercase()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'uppercase',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD','FIELD_DEFINITION'],
            'args' => [
                
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function getDirectives()
    {
        return [$this->directive_link(),$this->directive_external(),$this->directive_requires(),$this->directive_provides(),$this->directive_key(),$this->directive_shareable(),$this->directive_inaccessible(),$this->directive_override(),$this->directive_extends(),$this->directive_isAuthenticated(),$this->directive_hasRole(),$this->directive_pow(),$this->directive_uppercase()];
    }
        

}
